<?php

/**
 * @file
 * Contains alterations for kaupunkitieto search.
 */

declare(strict_types=1);
use Drupal\Core\Entity\FieldableEntityInterface;
use Drupal\Core\Field\FieldStorageDefinitionInterface;
use Drupal\paragraphs\ParagraphInterface;

/**
 * Implements hook_theme().
 */
function kaupunkitieto_search_theme($existing, $type, $theme, $path) {
  return [
    'header_search' => [
      'variables' => [
        'search_page_path' => '',
      ],
    ],
  ];
}

/**
 * Implements hook_helfi_hero_design_alter().
 */
function kaupunkitieto_helfi_hero_design_alter(array &$designs, FieldStorageDefinitionInterface $definition, FieldableEntityInterface|null $entity) : void {
  if ($entity instanceof ParagraphInterface) {
    $designs['with-search'] = t('With search');
  }
}
