packages:
    asm89/stack-cors: 1.3.0
    behat/mink: v1.10.0
    behat/mink-selenium2-driver: v1.6.0
    caxy/php-htmldiff: v0.1.14
    chi-teck/drupal-code-generator: 1.33.1
    city-of-helsinki/php-hauki-client: 1.2.0
    commerceguys/addressing: v1.4.1
    composer/ca-bundle: 1.3.4
    composer/composer: 2.2.18
    composer/installers: v1.12.0
    composer/metadata-minifier: 1.0.0
    composer/pcre: 1.0.1
    composer/semver: 3.3.2
    composer/spdx-licenses: 1.5.7
    composer/xdebug-handler: 3.0.3
    consolidation/annotated-command: 4.7.1
    consolidation/config: 1.2.1
    consolidation/filter-via-dot-access-data: 1.0.0
    consolidation/log: 2.1.1
    consolidation/output-formatters: 4.2.3
    consolidation/robo: 3.0.11
    consolidation/self-update: 2.0.5
    consolidation/site-alias: 3.1.7
    consolidation/site-process: 4.2.1
    cweagans/composer-patches: 1.7.2
    dealerdirect/phpcodesniffer-composer-installer: v0.7.2
    dflydev/dot-access-data: v1.1.0
    doctrine/annotations: 1.13.3
    doctrine/cache: 1.13.0
    doctrine/collections: 1.8.0
    doctrine/common: 2.13.3
    doctrine/deprecations: v1.0.0
    doctrine/event-manager: 1.2.0
    doctrine/inflector: 1.4.4
    doctrine/instantiator: 1.4.1
    doctrine/lexer: 1.2.3
    doctrine/persistence: 1.3.8
    doctrine/reflection: 1.2.3
    druidfi/omen: 0.2.1
    drupal/address: 1.11.0
    drupal/admin_toolbar: 2.5.0
    drupal/aet: 2.0.0-alpha6
    drupal/allowed_formats: 1.5.0
    drupal/api_tools: 1.0.0
    drupal/asset_injector: 2.13.0
    drupal/coder: 8.3.16
    drupal/config_filter: 2.4.0
    drupal/config_ignore: 2.3.0
    drupal/config_replace: 2.0.2
    drupal/config_rewrite: 1.5.0
    drupal/config_update: 1.7.0
    drupal/content_lock: 2.3.0
    drupal/core: 9.4.9
    drupal/core-composer-scaffold: 9.4.9
    drupal/core-dev: 9.4.9
    drupal/core-recommended: 9.4.9
    drupal/crop: 2.3.0
    drupal/ctools: 4.0.0
    drupal/default_content: 2.0.0-alpha2
    drupal/devel: 4.2.1
    drupal/diff: 1.1.0
    drupal/easy_breadcrumb: 2.0.4
    drupal/editoria11y: 1.0.14
    drupal/elasticsearch_connector: 7.0.0-alpha3
    drupal/entity: 1.4.0
    drupal/entity_browser: 2.8.0
    drupal/entity_reference_revisions: 1.10.0
    drupal/entity_usage: 2.0.0-beta7
    drupal/eu_cookie_compliance: 1.24.0
    drupal/external_entities: 2.0.0-alpha5
    drupal/externalauth: 2.0.3
    drupal/facets: 2.0.5
    drupal/features: 3.12.0
    drupal/field_group: 3.4.0
    drupal/filelog: 2.1.1
    drupal/focal_point: 1.5.0
    drupal/gin: 3.0.0-beta5
    drupal/gin_toolbar: 1.0.0-rc1
    drupal/hdbt: 4.3.5
    drupal/hdbt_admin: 1.8.4
    drupal/helfi_ahjo: 1.0.4
    drupal/helfi_api_base: 2.3.6
    drupal/helfi_hauki: 1.0.5
    drupal/helfi_linkedevents: 1.0.1
    drupal/helfi_media_formtool: 'dev-main:76646a8e31a822baf76400348dc703911e99d9f7'
    drupal/helfi_media_map: 1.0.2
    drupal/helfi_platform_config: 2.15.5
    drupal/helfi_tpr: 2.1.6
    drupal/helfi_tunnistamo: 2.2.3
    drupal/image_style_quality: 1.4.0
    drupal/imagecache_external: 3.0.1
    drupal/key_value_field: 1.3.0
    drupal/linkit: 6.0.0-beta3
    drupal/matomo: 1.19.0
    drupal/matomo_reports: 1.2.0
    drupal/media_entity_file_replace: 1.1.0
    drupal/media_entity_soundcloud: 3.1.1
    drupal/menu_block_current_language: 2.0.0-alpha1
    drupal/menu_link_attributes: 1.2.0
    drupal/metatag: 1.22.0
    drupal/oembed_providers: 2.1.0
    drupal/openid_connect: 3.0.0-alpha2
    drupal/paragraphs: 1.15.0
    drupal/paragraphs_asymmetric_translation_widgets: 1.1.0
    drupal/pathauto: 1.11.0
    drupal/publication_date: 2.0.0-beta7
    drupal/readonly_field_widget: 1.5.0
    drupal/redirect: 1.8.0
    drupal/role_delegation: 1.2.0
    drupal/scheduler: 1.4.0
    drupal/search_api: 1.28.0
    drupal/select2: 1.14.0
    drupal/simple_sitemap: 4.1.3
    drupal/siteimprove: 1.12.0
    drupal/social_media: 1.9.0-rc2
    drupal/stage_file_proxy: 1.5.0
    drupal/token: 1.11.0
    drupal/token_filter: 1.4.0
    drupal/translatable_menu_link_uri: 2.0.0
    drupal/twig_tweak: 3.2.0
    drupal/update_helper: 2.0.0
    drupal/view_unpublished: 1.0.0
    drupal/views_bulk_edit: 2.8.0
    drupal/views_bulk_operations: 4.2.1
    drupal/views_infinite_scroll: 2.0.1
    drush/drush: 10.6.2
    easyrdf/easyrdf: 1.1.1
    egulias/email-validator: 3.2.1
    elasticsearch/elasticsearch: v7.17.1
    enlightn/security-checker: v1.10.0
    ezimuel/guzzlestreams: 3.1.0
    ezimuel/ringphp: 1.2.2
    ezyang/htmlpurifier: v4.16.0
    friends-of-behat/mink-browserkit-driver: v1.6.1
    galbar/jsonpath: '2.1'
    grasmash/expander: 1.0.0
    grasmash/yaml-expander: 1.4.0
    guzzlehttp/guzzle: 6.5.8
    guzzlehttp/promises: 1.5.2
    guzzlehttp/psr7: 1.9.0
    instaclick/php-webdriver: 1.4.16
    joachim-n/composer-manifest: 1.1.5
    justinrainbow/json-schema: 5.2.12
    kint-php/kint: '3.3'
    laminas/laminas-diactoros: 2.11.3
    laminas/laminas-escaper: 2.9.0
    laminas/laminas-feed: 2.17.0
    laminas/laminas-stdlib: 3.7.1
    league/container: 3.4.1
    league/uri: 6.8.0
    league/uri-interfaces: 2.3.0
    makinacorpus/php-lucene: 1.2.0
    masterminds/html5: 2.7.6
    mikey179/vfsstream: v1.6.11
    mkalkbrenner/php-htmldiff-advanced: 0.0.8
    myclabs/deep-copy: 1.11.0
    nikic/php-parser: v4.15.2
    nodespark/des-connector: '7.x-dev:a075a6b9e54b5855d0a292d9266839312e6026dc'
    nyholm/dsn: 2.0.1
    pear/archive_tar: 1.4.14
    pear/console_getopt: v1.4.3
    pear/pear-core-minimal: v1.10.11
    pear/pear_exception: v1.0.2
    phar-io/manifest: 2.0.3
    phar-io/version: 3.2.1
    phpdocumentor/reflection-common: 2.2.0
    phpdocumentor/reflection-docblock: 5.3.0
    phpdocumentor/type-resolver: 1.6.2
    phpspec/prophecy: v1.16.0
    phpspec/prophecy-phpunit: v2.0.1
    phpstan/phpdoc-parser: 1.13.1
    phpunit/php-code-coverage: 9.2.20
    phpunit/php-file-iterator: 3.0.6
    phpunit/php-invoker: 3.1.1
    phpunit/php-text-template: 2.0.4
    phpunit/php-timer: 5.0.3
    phpunit/phpunit: 9.4.4
    platformsh/config-reader: 2.4.0
    psr/cache: 1.0.1
    psr/container: 1.1.2
    psr/http-factory: 1.0.1
    psr/http-message: 1.0.1
    psr/log: 1.1.4
    psy/psysh: v0.10.12
    ralouphie/getallheaders: 3.0.3
    react/promise: v2.9.0
    ruflin/elastica: 7.3.0
    sebastian/cli-parser: 1.0.1
    sebastian/code-unit: 1.0.8
    sebastian/code-unit-reverse-lookup: 2.0.3
    sebastian/comparator: 4.0.8
    sebastian/complexity: 2.0.2
    sebastian/diff: 4.0.4
    sebastian/environment: 5.1.4
    sebastian/exporter: 4.0.5
    sebastian/global-state: 5.0.5
    sebastian/lines-of-code: 1.0.3
    sebastian/object-enumerator: 4.0.4
    sebastian/object-reflector: 2.0.4
    sebastian/recursion-context: 4.0.4
    sebastian/resource-operations: 3.0.3
    sebastian/type: 2.3.4
    sebastian/version: 3.0.2
    seld/jsonlint: 1.9.0
    seld/phar-utils: 1.2.1
    sirbrillig/phpcs-variable-analysis: v2.11.9
    slevomat/coding-standard: 8.6.4
    squizlabs/php_codesniffer: 3.7.1
    stack/builder: v1.0.6
    symfony-cmf/routing: 2.3.4
    symfony/browser-kit: v4.4.44
    symfony/console: v4.4.49
    symfony/css-selector: v4.4.44
    symfony/debug: v4.4.44
    symfony/dependency-injection: v4.4.49
    symfony/deprecation-contracts: v2.5.2
    symfony/dom-crawler: v4.4.45
    symfony/error-handler: v4.4.44
    symfony/event-dispatcher: v4.4.44
    symfony/event-dispatcher-contracts: v1.1.13
    symfony/filesystem: v4.4.42
    symfony/finder: v4.4.44
    symfony/http-client-contracts: v2.5.2
    symfony/http-foundation: v4.4.49
    symfony/http-kernel: v4.4.49
    symfony/lock: v4.4.46
    symfony/mime: v5.4.13
    symfony/phpunit-bridge: v5.4.16
    symfony/polyfill-ctype: v1.25.0
    symfony/polyfill-iconv: v1.25.0
    symfony/polyfill-intl-idn: v1.25.0
    symfony/polyfill-intl-normalizer: v1.25.0
    symfony/polyfill-mbstring: v1.25.0
    symfony/polyfill-php72: v1.27.0
    symfony/polyfill-php73: v1.27.0
    symfony/polyfill-php80: v1.25.0
    symfony/process: v4.4.44
    symfony/psr-http-message-bridge: v2.1.4
    symfony/routing: v4.4.44
    symfony/serializer: v4.4.47
    symfony/service-contracts: v2.5.2
    symfony/translation: v4.4.47
    symfony/translation-contracts: v2.5.2
    symfony/validator: v4.4.48
    symfony/var-dumper: v5.4.14
    symfony/yaml: v4.4.45
    t4web/composer-lock-parser: 1.2.0
    theseer/tokenizer: 1.2.1
    twig/twig: v2.15.3
    typo3/phar-stream-wrapper: v3.1.7
    webflo/drupal-finder: 1.2.2
    webmozart/assert: 1.11.0
    webmozart/path-util: 2.3.0
