services:
  _defaults:
    autowire: true
    autoconfigure: true

  Drupal\kaupunkitieto_config\EventSubscriber\CspEventSubscriber:
      class: Drupal\kaupunkitieto_config\EventSubscriber\CspEventSubscriber
