config_rewrite:
  replace: ['dependencies', 'hidden']
dependencies:
  config:
    - field.field.node.page.field_author
    - field.field.node.page.field_content
    - field.field.node.page.field_has_hero
    - field.field.node.page.field_hero
    - field.field.node.page.field_lead_in
    - field.field.node.page.field_liftup_image
    - field.field.node.page.field_lower_content
    - field.field.node.page.field_metatags
    - field.field.node.page.field_search_result_text
    - field.field.node.page.field_sidebar_content
    - node.type.page
  module:
    - hdbt_admin_tools
    - media_library
    - metatag
    - paragraphs
    - path
    - publication_date
    - scheduler
content:
  field_author:
    type: entity_reference_autocomplete
    weight: 52
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: { }
  field_search_result_text:
    type: string_textarea
    weight: 53
    region: content
    settings:
      rows: 5
      placeholder: ''
    third_party_settings: { }
hidden: {  }
