config_rewrite:
  replace: ['hidden','dependencies']
dependencies:
  config:
    - field.field.node.landing_page.field_author
    - field.field.node.landing_page.field_content
    - field.field.node.landing_page.field_has_hero
    - field.field.node.landing_page.field_hero
    - field.field.node.landing_page.field_is_category
    - field.field.node.landing_page.field_keywords
    - field.field.node.landing_page.field_liftup_image
    - field.field.node.landing_page.field_metatags
    - node.type.landing_page
  module:
    - entity_reference_revisions
    - metatag
    - user
content:
  field_author:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: { }
    weight: 4
    region: content
hidden:
  field_has_hero: true
  field_hero: true
  field_is_category: true
  field_keywords: true
  field_liftup_image: true
  langcode: true
  published_at: true
  search_api_excerpt: true
  toc_enabled: true
