config_rewrite:
  replace: ['hidden','dependencies']
dependencies:
  config:
    - field.storage.node.field_content
    - node.type.page
    - paragraphs.paragraphs_type.accordion
    - paragraphs.paragraphs_type.columns
    - paragraphs.paragraphs_type.content_cards
    - paragraphs.paragraphs_type.content_liftup
    - paragraphs.paragraphs_type.content_menu
    - paragraphs.paragraphs_type.embed
    - paragraphs.paragraphs_type.image
    - paragraphs.paragraphs_type.list_of_links
    - paragraphs.paragraphs_type.text
  module:
    - entity_reference_revisions
