config_rewrite:
  replace: ['dependencies']
dependencies:
  config:
    - field.storage.paragraph.field_content_cards_content
    - node.type.article
    - node.type.landing_page
    - node.type.page
    - paragraphs.paragraphs_type.content_cards
settings:
  handler_settings:
    target_bundles:
      article: article
