config_rewrite:
  replace: ['hidden','dependencies']
dependencies:
  config:
    - field.storage.node.field_content
    - node.type.landing_page
    - paragraphs.paragraphs_type.banner
    - paragraphs.paragraphs_type.columns
    - paragraphs.paragraphs_type.content_cards
    - paragraphs.paragraphs_type.content_liftup
    - paragraphs.paragraphs_type.embed
    - paragraphs.paragraphs_type.infograph
    - paragraphs.paragraphs_type.liftup_with_image
    - paragraphs.paragraphs_type.list_of_links
  module:
    - entity_reference_revisions
